FROM maven:3.6.0-jdk-8 as MAVEN_CHAIN

RUN     mkdir -p /build

WORKDIR /build

COPY    pom.xml /build
COPY    testng.xml /build

RUN mvn -B dependency:resolve dependency:resolve-plugins

COPY    src /build/src

RUN mvn clean test

FROM tomcat:9.0-jre8-alpine

COPY --from=MAVEN_CHAIN /build/target $CATALINA_HOME/webapps/target

EXPOSE 8080

CMD ["catalina.sh","run"]