FROM maven:3.6.0-jdk-8 as builder

RUN     mkdir -p /build

WORKDIR /build

COPY    pom.xml /build
COPY    testng.xml /build

RUN mvn -B dependency:resolve dependency:resolve-plugins


COPY    src /build/src

CMD ["mvn","clean","test"]