FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8080
ADD target/springbootbddcucumber-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Xmx512m","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=local","-jar","/app.jar"]